### ISSUE TITLE
Simplify CSS code for font-weight property.

### ISSUE THREAD

**Issue by josephtkim** [normcler/prj-rev-bwfs-dasmoto#5]
It is a good idea to simplify the CSS code for shared properties to make the code less repetitive and cleaner. The font-weight property can be applied to all the elements at once rather than individually, like so or to the body selector as well.

```css
#top-header h1, .product h2, .product .bold-span {
  font-weight: bold;
}
```
